version: "3.8"
name: taskforce

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:

services:
  php:
    container_name: ${PROJECT_SLUG}_php
    build:
      context: ./.docker/php
    networks: [app_network]
    volumes:
      - .:/app

  nginx:
    container_name: ${PROJECT_SLUG}_nginx
    image: ${NGINX_DOCKER_IMAGE}
    networks: [app_network]
    depends_on:
      - php
    ports:
      - "${NGINX_PORT:-8080}:80"
    volumes:
      - .:/app
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  mysql:
    container_name: ${PROJECT_SLUG}_db
    image: ${MYSQL_DOCKER_IMAGE:-mysql:8.0.43}
    networks: [app_network]
    ports:
      - "${MYSQL_PORT:-3380}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-app}
      MYSQL_USER: ${MYSQL_USER:-app}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-secret}
